In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('titanic.csv', sep=',')

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df['Travelalone'] = np.where((df['SibSp'] + df['Parch'])> 0,0,1).astype('uint8')

In [8]:
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked  Travelalone
0        0         A/5 21171   7.2500   NaN        S            0
1        0          PC 17599  71.2833   C85        C            0
2        0  STON/O2. 3101282   7.9250   NaN        S            1
3        0            113803  53.1000  C123        S            0
4        0            373450   8.0500   NaN        S            1
..     ...               ...      ...   ...      ...          ...
886      0            211536  13.0000   NaN        S            1
887      0            112053  30.0000   B42        S            1
888      2        W./C. 6607  23.4500   NaN        S            0
889      0            111369  30.0000  C148        C            1
890      0            370376   7.7500   NaN        Q            1

[891 rows x 13 columns]

In [9]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Travelalone
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Travelalone  891 non-null    uint8
dtypes: float64(2), int64(5), object(5), uint8(1)
memory usage: 84.5+ KB

In [11]:
df1 = df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin'], axis=1)

In [12]:
df1.head()

   Survived  Pclass     Sex   Age     Fare Embarked  Travelalone
0         0       3    male  22.0   7.2500        S            0
1         1       1  female  38.0  71.2833        C            0
2         1       3  female  26.0   7.9250        S            1
3         1       1  female  35.0  53.1000        S            0
4         0       3    male  35.0   8.0500        S            1

In [13]:
df1.isna().sum()

Survived         0
Pclass           0
Sex              0
Age            177
Fare             0
Embarked         2
Travelalone      0
dtype: int64

In [14]:
df1['Age'] = df1['Age'].fillna(df1['Age'].median())

In [15]:
df1.isna().sum()

Survived       0
Pclass         0
Sex            0
Age            0
Fare           0
Embarked       2
Travelalone    0
dtype: int64

In [16]:
# Age was having numeric values hence missing values were replaced with median of Age while Embarked is having categorical value so cannot be replaced ith mean etc i.e. numeric values.

In [17]:
df1.describe()

         Survived      Pclass         Age        Fare  Travelalone
count  891.000000  891.000000  891.000000  891.000000   891.000000
mean     0.383838    2.308642   29.361582   32.204208     0.602694
std      0.486592    0.836071   13.019697   49.693429     0.489615
min      0.000000    1.000000    0.420000    0.000000     0.000000
25%      0.000000    2.000000   22.000000    7.910400     0.000000
50%      0.000000    3.000000   28.000000   14.454200     1.000000
75%      1.000000    3.000000   35.000000   31.000000     1.000000
max      1.000000    3.000000   80.000000  512.329200     1.000000

In [18]:
df2 = df.drop(['Pclass','Embarked'], axis=1)

In [19]:
df2

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Travelalone
0,1,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,0
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,0
2,3,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,1
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,0
4,5,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,1
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,1
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,0
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,1
890,891,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,1

In [20]:
df3 = df1.drop(['Survived'], axis =1)

In [21]:
df3.head()

   Pclass     Sex   Age     Fare Embarked  Travelalone
0       3    male  22.0   7.2500        S            0
1       1  female  38.0  71.2833        C            0
2       3  female  26.0   7.9250        S            1
3       1  female  35.0  53.1000        S            0
4       3    male  35.0   8.0500        S            1

In [22]:
df3.isna().sum()

Pclass         0
Sex            0
Age            0
Fare           0
Embarked       2
Travelalone    0
dtype: int64

In [23]:
# get_dummies method on categorical values to make them numeric

df_titanic = pd.get_dummies(df1, columns=['Pclass', 'Embarked', 'Sex'], drop_first= True, dtype=int)

In [24]:
df_titanic.head()

,Survived,Age,Fare,Travelalone,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Sex_male
0,0,22.0,7.2500,0,0,1,0,1,1
1,1,38.0,71.2833,0,0,0,0,0,0
2,1,26.0,7.9250,1,0,1,0,1,0
3,1,35.0,53.1000,0,0,0,0,1,0
4,0,35.0,8.0500,1,0,1,0,1,1

In [30]:
X = df_titanic.drop(['Survived'], axis=1)
y = df_titanic['Survived']

In [31]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [32]:
trans_MM = MinMaxScaler()
trans_SS = StandardScaler()

In [33]:
df_MM = trans_MM.fit_transform(X)
pd.DataFrame(df_MM)

            0         1    2    3    4    5    6    7
0    0.271174  0.014151  0.0  0.0  1.0  0.0  1.0  1.0
1    0.472229  0.139136  0.0  0.0  0.0  0.0  0.0  0.0
2    0.321438  0.015469  1.0  0.0  1.0  0.0  1.0  0.0
3    0.434531  0.103644  0.0  0.0  0.0  0.0  1.0  0.0
4    0.434531  0.015713  1.0  0.0  1.0  0.0  1.0  1.0
..        ...       ...  ...  ...  ...  ...  ...  ...
886  0.334004  0.025374  1.0  1.0  0.0  0.0  1.0  1.0
887  0.233476  0.058556  1.0  0.0  0.0  0.0  1.0  0.0
888  0.346569  0.045771  0.0  0.0  1.0  0.0  1.0  0.0
889  0.321438  0.058556  1.0  0.0  0.0  0.0  0.0  1.0
890  0.396833  0.015127  1.0  0.0  1.0  1.0  0.0  1.0

[891 rows x 8 columns]

In [34]:
df_SS = trans_SS.fit_transform(X)
pd.DataFrame(df_SS)

,0,1,2,3,4,5,6,7
0,-0.565736,-0.502445,-1.231645,-0.510152,0.902587,-0.307562,0.619306,0.737695
1,0.663861,0.786845,-1.231645,-0.510152,-1.107926,-0.307562,-1.614710,-1.355574
2,-0.258337,-0.488854,0.811922,-0.510152,0.902587,-0.307562,0.619306,-1.355574
3,0.433312,0.420730,-1.231645,-0.510152,-1.107926,-0.307562,0.619306,-1.355574
4,0.433312,-0.486337,0.811922,-0.510152,0.902587,-0.307562,0.619306,0.737695
...,...,...,...,...,...,...,...,...
886,-0.181487,-0.386671,0.811922,1.960202,-1.107926,-0.307562,0.619306,0.737695
887,-0.796286,-0.044381,0.811922,-0.510152,-1.107926,-0.307562,0.619306,-1.355574
888,-0.104637,-0.176263,-1.231645,-0.510152,0.902587,-0.307562,0.619306,-1.355574
889,-0.258337,-0.044381,0.811922,-0.510152,-1.107926,-0.307562,-1.614710,0.737695
890,0.202762,-0.492378,0.811922,-0.510152,0.902587,3.251373,-1.614710,0.737695

In [35]:
 from sklearn.datasets import make_classification
 from sklearn.model_selection import train_test_split, KFold, cross_val_score
 from sklearn.tree import DecisionTreeClassifier
 import matplotlib.pyplot as plt
 import numpy as np

In [36]:
# Generating a synthetic dataset
X,y = make_classification(n_samples=9000, n_features=18, n_informative=4, n_redundant=12, random_state=2)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3)

In [38]:
# Setup k-fold cross validation
kf= KFold(n_splits=5, shuffle=True, random_state=42)
depths= list(range(1,21))
cv_scores = []

# Loop through various depths
for depth in depths:
  model = DecisionTreeClassifier(max_depth=depth)
  scores = cross_val_score(model,X_train,y_train,cv=kf, scoring='accuracy')
  cv_scores.append(scores.mean())

In [40]:
best_depth = depths[np.argmax(cv_scores)]
print(f'Best depth based on cross-validation: {best_depth}')

Best depth based on cross-validation: 9

In [42]:
# Train and evaluate optimal model

model = DecisionTreeClassifier(max_depth=best_depth)
model.fit(X_train, y_train)

train_accuracy = model.score(X_train, y_train)
test_accuracy = model.score(X_test, y_test)

print(f'Training Accuracy: {train_accuracy:.3f}')
print(f'Testing Accuracy: {test_accuracy:.3f}')

Training Accuracy: 0.941
Testing Accuracy: 0.887